# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Healto' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Vector Icons Configuration for iOS
    installer.pods_project.targets.each do |target|
      if target.name == 'RNVectorIcons'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',
            'RN_FONT_AWESOME=1',
            'RN_MATERIAL_COMMUNITY=1',
            'RN_MATERIAL_ICONS=1',
            'RN_IONICONS=1',
            'RN_FEATHER=1',
            'RN_ENTYPO=1',
            'RN_ZOCIAL=1',
            'RN_SIMPLE_LINE_ICONS=1',
            'RN_FOUNDATION=1',
            'RN_EVIL_ICONS=1',
            'RN_ANT_DESIGN=1',
          ]
        end
      end
    end
  end
end
